FROM mcr.microsoft.com/playwright/python:v1.42.0-jammy

WORKDIR /app

# 安裝 Python 依賴
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 複製專案程式碼
COPY . .

# 預設執行指令
CMD ["python", "main.py"]
